### PR TITLE
Support for Laravel 8.0

### PR DESCRIPTION
**Pull request by MimisK13**
## Description

Add Support for Laravel 8.0

### CODE REVIEW

**Comment by chaseconey** [comment]
@MimisK13 any chance we can get this merged?

**Comment by chaseconey** [comment]
@ChristianKuri any chance we could get this merged?

**Comment by ChristianKuri** [comment]
Does anyone cant use this package unless this is merged? and what's the exact change that needs to be made?

**Comment by MimisK13** [comment]
There is no need to make any changes to the code. You can ignore this PR and just add some more versions.

Something like that
```json
        "illuminate/support": ">=5.4|^8.0",
        "illuminate/database": ">=5.4|^8.0",
        "php" : ">=5.6.4|^7.2"
```

Take a look at Files Change for versions.

**Comment by ChristianKuri** [comment]
The >=5.4 means that anything above or equal to 5.4 will work, that includes 6.0, 7.0, 8.0 and above, if I see that in the future a major version breaks the package I can simply limit that version or update my code and include that version.

Thank you for your pull request!

**Comment by MimisK13** [comment]
@ChristianKuri you must update ```orchestra/testbench```

```json
    "require-dev": {
        "orchestra/testbench": "~3.4",	        "orchestra/testbench": "~3.4|^5.0|^6.0",
    },	   
```

Currently not compatible with Laravel 8.

**Pull request closed without merging**
